config/routes.rb
Rails.application.routes.draw do
  
  resources :assignments 
  
  resources :submits, only: [:index, :new, :create, :destroy]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
    has_many :submits, dependent: :destroy
end

app/models/submit.rb
class Submit < ActiveRecord::Base
    belongs_to :assignment
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    def index
     @assignments = Assignment.all
   end
   
   
   def show
     @assignment = Assignment.find(params[:id])
   end

 def new
     @assignment = Assignment.new
   end  

   def create
     @assignment = Assignment.new
     @assignment.name = params[:assignment][:name]
     @assignment.description = params[:assignment][:description]
     @assignment.public = params[:assignment][:public]
 
     if @assignment.save
       flash[:notice] = "Assignment was saved successfully."
       redirect_to @assignment
     else
       flash.now[:alert] = "Error creating assignment. Please try again."
       render :new
     end
   end
   
     def edit
     @assignment = Assignment.find(params[:id])
   end
 
 def update
     @assignment = Assignment.find(params[:id])
 
     @assignment.name = params[:assignment][:name]
     @assignment.description = params[:assignment][:description]
     @assignment.public = params[:assignment][:public]
 
     if @assignment.save
        flash[:notice] = "Assignment was updated successfully."
       redirect_to @assignment
     else
       flash.now[:alert] = "Error saving assignment. Please try again."
       render :edit
     end
   end
   
   def destroy
     @assignment = Topic.find(params[:id])
 
     if @assignment.destroy
       flash[:notice] = "\"#{@assignment.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the assignment."
       render :show
     end
   end
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  def index
      @submits = Submit.all
  end
  
  def show
     @submit = Submit.find(params[:id])
   end
   
   def new
      @submit = Submit.new
   end
   
   def create
      @submit = Submit.new(submit_params)
      
      if @submit.save
         redirect_to submits_path, notice: "The assignment #{@submit.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
      @submit = Submit.find(params[:id])
      @submit.destroy
      redirect_to submits_path, notice:  "The assignment #{@submit.name} has been deleted."
   end
   
   private
      def submit_params
      params.require(:submit).permit(:name, :attachment)
      end
   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignments/edit.html.erb
 <h1>Edit Assignment</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @assignment do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter assignment name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter assignment description" %>
       </div>
       <div class="form-group">
 <!-- #11 -->
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public assignment
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/assignments/index.html.erb
<h1>Assignments</h1>
 
 <div class="row">
   <div class="col-md-8">
 <!-- #7 -->
     <% @assignments.each do |assignment| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
 <!-- #8 -->
             <%= link_to assignment.name, assignment %>
           </h4>
           <small>
             <%= assignment.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
 <!-- #9 -->
     <%= link_to "New Assignment", new_assignment_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/assignments/new.html.erb
 <h1>New Assignment</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @assignment do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter assignment name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter assignment description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public assignment
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/assignments/show.html.erb
 <h1><%= @assignment.name %>
 
 <%= link_to "Edit Assignment", edit_assignment_path, class: 'btn btn-success' %>
 <%= link_to "Delete Assignment", @assignment, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this assignment?' } %>
 </h1>
 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @assignment.description %></p>
 <!-- #10 -->
     <% @assignment.submits.each do |submit| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to submit.name, submit %>
           </h4>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "Submit Assignment", new_submit_path(@assignment), class: 'btn btn-success' %>
   </div>
 </div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html>
 <head>
   <title>Insurance Adjuster School</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag    "application", media: "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
 </head>
 <body>
   <div class="container">
     <ul class="nav nav-tabs">
       <li><%= link_to "Blog", welcome_index_path %></li>
       <li><%= link_to "About", welcome_about_path %></li>
       <li><%= link_to "Assignments", assignments_path %></li>
     </ul>

     <%= yield %>
   </div>

 </body>
 </html>

app/views/submits/create.html.erb
<h1>Submits#create</h1>
<p>Find me in app/views/submits/create.html.erb</p>

app/views/submits/destroy.html.erb
<h1>Submits#destroy</h1>
<p>Find me in app/views/submits/destroy.html.erb</p>

app/views/submits/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "Submit Assignment", new_submit_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @submits.each do |submit| %>
         
         <tr>
            <td><%= submit.name %></td>
            <td><%= link_to "Download Assignment", submit.attachment_url %></td>
            <td><%= button_to "Delete",  submit, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{submit.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/submits/new.html.erb
<% if !@submit.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @submit.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @submit, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/submits/show.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "Submit Assignment", new_submit_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @submits.each do |submit| %>
         
         <tr>
            <td><%= submit.name %></td>
            <td><%= link_to "Download Assignment", submit.attachment_url %></td>
            <td><%= button_to "Delete",  submit, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{submit.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/welcome/about.html.erb
 <h1>About Adjuster</h1>
 <p>Made for students to submit their work to teachers</p>

app/views/welcome/index.html.erb
 <h1>Welcome to Adjuster</h1>
 <p>Sign-up to submit assignments.</p>